export const EXAMPLES = [
  {
    id: "acme",
    accountName: "Acme Corp",
    tag: "Watch",
    blurb: "Strong champion, but outcomes and exec engagement are slipping.",
    inputs: {
      activeUsersPct: 78,
      coreFeaturesPct: 65,
      usageTrendPct: -18,
      milestonesAchieved: 2,
      milestonesTotal: 4,
      roi: "partial",
      champion: "strong",
      execSponsor: "medium",
      meetingAttendancePct: 90,
      csat: 4.2,
      nps: 32,
      openCriticalIssues: 1,
      openTotalIssues: 7,
      previousOverallScore: 80,
    },
  },
  {
    id: "meridian",
    accountName: "Meridian Health",
    tag: "Healthy",
    blurb: "Renewed early, full exec buy-in, low support burden.",
    inputs: {
      activeUsersPct: 92,
      coreFeaturesPct: 88,
      usageTrendPct: 6,
      milestonesAchieved: 4,
      milestonesTotal: 4,
      roi: "full",
      champion: "strong",
      execSponsor: "strong",
      meetingAttendancePct: 95,
      csat: 4.7,
      nps: 58,
      openCriticalIssues: 0,
      openTotalIssues: 2,
      previousOverallScore: 88,
    },
  },
  {
    id: "foundry",
    accountName: "Foundry Retail Group",
    tag: "At risk",
    blurb: "Usage collapsing, no ROI story, three critical tickets open.",
    inputs: {
      activeUsersPct: 35,
      coreFeaturesPct: 22,
      usageTrendPct: -40,
      milestonesAchieved: 0,
      milestonesTotal: 3,
      roi: "none",
      champion: "weak",
      execSponsor: "weak",
      meetingAttendancePct: 40,
      csat: 2.1,
      nps: -35,
      openCriticalIssues: 3,
      openTotalIssues: 12,
      previousOverallScore: 55,
    },
  },
];

export const BLANK_INPUTS = {
  activeUsersPct: 70,
  coreFeaturesPct: 70,
  usageTrendPct: 0,
  milestonesAchieved: 1,
  milestonesTotal: 2,
  roi: "partial",
  champion: "medium",
  execSponsor: "medium",
  meetingAttendancePct: 75,
  csat: 3.5,
  nps: 10,
  openCriticalIssues: 0,
  openTotalIssues: 2,
  previousOverallScore: "",
};
